var CANVAS_WIDTH = 1920;
var CANVAS_HEIGHT = 1080;

var EDGEBOARD_X = 338;
var EDGEBOARD_Y = 97;

var FPS_TIME = 1000 / 24;
var DISABLE_SOUND_MOBILE = false;

var FONT_GAME_1 = 'ArialBold';
var FONT_GAME_2 = 'Digital-7';

var STATE_LOADING = 0;
var STATE_SPLASH = 6;
var STATE_MENU = 1;
var STATE_HELP = 1;
var STATE_GAME = 3;

var STATE_GAME_WAITING_FOR_BET = 0;
var STATE_GAME_DEALING = 1;
var STATE_GAME_HITTING = 2;
var STATE_GAME_SPLIT = 3;
var STATE_GAME_FINALIZE = 4;
var STATE_GAME_SHOW_WINNER = 5;
var STATE_GAME_CLEAR_RESULT = 6;
var STATE_GAME_DEAL_FITCH = 7;

var STATE_CARD_DEALING = 0;
var STATE_CARD_SPLIT = 1;
var STATE_CARD_REMOVING = 2;
var SOUNDTRACK_VOLUME_IN_GAME = 0.5;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END = 5;

var SIT_DOWN = 'SIT_DOWN';
var PASS_TURN = 'PASS_TURN';
var PLAYER_LOSE = 'PLAYER_LOSE';
var ASSIGN_FICHES = 'ASSIGN_FICHES';
var FICHES_END_MOV = 'FICHES_END_MOV';
var RESTORE_ACTION = 'RESTORE_ACTION';
var END_HAND = 'END_HAND';
var ON_CARD_SHOWN = 'ON_CARD_SHOWN';
var ON_CARD_ANIMATION_ENDING = 'ON_CARD_ANIMATION_ENDING';
var SPLIT_CARD_END_ANIM = 'SPLIT_CARD_END_ANIM';
var ON_CARD_TO_REMOVE = 'ON_CARD_TO_REMOVE';

var NUM_FICHES = 6;
var CARD_WIDTH = 162;
var CARD_HEIGHT = 247;
var MIN_BET;
var MAX_BET;
var TOTAL_MONEY;
var FICHE_WIDTH;

var TIME_FICHES_MOV = 600;
var TIME_CARD_DEALING = 250;
var TIME_CARD_REMOVE = 500;
var TIME_SHOW_FINAL_CARDS = 1500;//4000;
var TIME_END_HAND = 1500;
var BET_TIME = 10000;
var AD_SHOW_COUNTER;
var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;
var SHOW_CREDITS;

var CURRENCY_DECIMAL = 2; //default currency decimal is 2
var FONT_RED_HAT_DISPLAY_REGULAR = 'RedHatDisplay-Regular';
var FONT_RED_HAT_DISPLAY_BLACK = 'RedHatDisplay-Black';
var FONT_RED_HAT_DISPLAY_BOLD = 'RedHatDisplay-Bold';
var FONT_REGULAR = 'BAHNSCHRIFT';
var FONT_SEMI_BOLD = 'BAHNSCHRIFT_SEMIBOLD';
