//for testing
// var _aEnlights;

var CANVAS_WIDTH = 1280;
var CANVAS_HEIGHT = 768;
// var CANVAS_WIDTH = 1920;
// var CANVAS_HEIGHT = 1080;

//for 1280x768
var EDGEBOARD_X = 90;
var EDGEBOARD_Y = 95;

//for 19020x1080
// var EDGEBOARD_X = 338;
// var EDGEBOARD_Y = 97;

var FPS = 30;
var FPS_TIME = 1000 / FPS;
var DISABLE_SOUND_MOBILE = false;

var STATE_LOADING = 0;
var STATE_MENU = 1;
var STATE_HELP = 1;
var STATE_GAME = 3;

var STATE_GAME_WAITING_FOR_BET = 0;
var STATE_GAME_COME_OUT = 1;
var STATE_GAME_COME_POINT = 2;

var ON_SHOW_BET_ON_TABLE = 0;
var ON_SHOW_ENLIGHT = 1;
var ON_HIDE_ENLIGHT = 2;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END = 5;
var ON_CONTROLLER_END = 6;
var ON_CONTROLLER_REMOVE = 7;
var ON_CONTROLLER_ROLL = 8;

var TOTAL_MONEY;
var NUM_FICHES = 6;
var MIN_BET;
var MAX_BET;
var WIN_OCCURRENCE;
var TIME_FICHES_MOV = 1500;
var TIME_SHOW_DICES_RESULT;

var NUM_DICE_ROLLING_FRAMES = 34;
// var NUM_DICE_ROLLING_FRAMES = 150;
var NUM_BALL_SPIN_FRAMES = 200;
var NUM_HAND_FOR_ADS;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;
var SHOW_CREDITS;

var FONT1 = "arialbold";
var FONT2 = "Digital-7";
// var FONT3 = "BAHNSCHRIFT";
var FONT_REGULAR = "BAHNSCHRIFT";
var FONT_SEMI_BOLD = "BAHNSCHRIFT_SEMIBOLD";

var BASE_URL = "https://api.gamessecure.com";