//#region - Class defination 
class Constant {
    constructor() {
        // this.numberOfGames = 4;
        this.gameNameArray = [
            { name: "CopterGame", nameToShow: "Copter Ride", url: "https://game.redappletech.info/CopterGame/?timer=180", image: "images/copter_ride.png" },
            { name: "ConnectTheBall", nameToShow: "Connect The Ball", url: "https://game.redappletech.info/ConnectTheBall/?timer=180", image: "images/connect_the_ball.png" },
            { name: "TapTapShots", nameToShow: "Tap Tap Shots", url: "https://game.redappletech.info/TapTapShots/?timer=180", image: "images/tap_tap_shot.png" },
            { name: "CutTheRope", nameToShow: "Cut The Rope", url: "https://game.redappletech.info/CutTheRope/", image: "images/cut_the_rope.png" },
            { name: "EggyCar", nameToShow: "Eggy Car", url: "https://game.redappletech.info/EggyCar/?timer=180", image: "images/eggy_car.png" },
            { name: "HitItRight", nameToShow: "Hit It Right", url: "https://game.redappletech.info/HitItRightAndroidiOS/", image: "./images/hit_it_right.png" },
            { name: "CityBlocks", nameToShow: "City Blocks", url: "https://game.redappletech.info/CityBlocks/?timer=180", image: "./images/city_blocks.png" },
            { name: "BirdFurys", nameToShow: "Bird Fury's", url: "https://game.redappletech.info/BirdFurys/", image: "images/bird_furys.png" },
            { name: "BeastCharge", nameToShow: "Beast Charge", url: "https://game.redappletech.info/BeastCharge/", image: "images/beast_charge.png" },
            { name: "BoatCraze", nameToShow: "Boat Craze", url: "https://game.redappletech.info/BoatCraze/", image: "images/boat_craze.png" },
            { name: "BubblyPetBurst", nameToShow: "Bubbly Pet Burst", url: "https://game.redappletech.info/BubblyPetBurst/", image: "images/bubble_pet.png" },
            { name: "HeadyGoals", nameToShow: "Heady Goals", url: "https://game.redappletech.info/HeadyGoals/", image: "images/heady_goals.png" },
            { name: "MinersQuest", nameToShow: "Miner's Quest", url: "https://game.redappletech.info/MinersQuest/", image: "images/miners_quest.png" },
            { name: "CandyLines", nameToShow: "Candy Lines", url: "https://game.redappletech.info/CandyLines/", image: "images/candy_lines.png" },
            { name: "FrenzyShapes", nameToShow: "Frenzy Shapes", url: "https://game.redappletech.info/FrenzyShapes/", image: "images/frenzy_shapes.png" },
            { name: "RocketSaviour", nameToShow: "Rocket Saviour", url: "https://game.redappletech.info/RocketSaviour/", image: "images/rocket_saviour.png" },
            { name: "SlingyTombRush", nameToShow: "Slingy Tomb Rush", url: "https://game.redappletech.info/SlingyTombRush/", image: "images/slingy_tomb_rush.png" },
            { name: "WheelyEggy", nameToShow: "Wheely Eggy", url: "https://game.redappletech.info/WheelyEggy/", image: "images/wheely_eggy.png" },
            { name: "RollingCart", nameToShow: "Rolling Cart", url: "https://game.redappletech.info/RollingCart/?timer=180", image: "images/rolling_cart.png" },
            { name: "WordSearch", nameToShow: "Word Search", url: "https://game.redappletech.info/WordSearchJG/?timer=180", image: "images/word_search.png" },
            { name: "SuperBird", nameToShow: "Super Bird", url: "https://game.redappletech.info/SuperBird/?timer=180", image: "./images/super_bird.jpg" },
            { name: "JumpItRight", nameToShow: "Jump It Right", url: "https://game.redappletech.info/JumpItRight/", image: "./images/jump_it_right.png" },
            { name: "CatchTheLower", nameToShow: "Catch The Lower", url: "https://game.redappletech.info/CatchTheLower/", image: "images/catch_the_lower.png" },
            { name: "FireBall", nameToShow: "Fire Ball", url: "https://game.redappletech.info/FireBall/", image: "images/fire_ball.png" },
            { name: "HitBall", nameToShow: "Hit Ball", url: "https://game.redappletech.info/HitBall/", image: "images/hit_ball.png" },
            { name: "DontDrop", nameToShow: "Dont Drop", url: "https://game.redappletech.info/DontDrop/", image: "images/dont_drop.png" },
            { name: "FlyItRight", nameToShow: "Fly It Right", url: "https://game.redappletech.info/FlyItRight/", image: "images/fly_it_right.png" },
            { name: "MatchItRight", nameToShow: "Match It Right", url: "https://game.redappletech.info/MatchItRight/", image: "images/match_it_right.png" },
            { name: "JustGame_Cricket", nameToShow: "Cricket Master", url: "https://game.redappletech.info/JustGame_Cricket/", image: "images/cricket_master.png" },
            { name: "BeerGame", nameToShow: "Beer Game", url: "https://game.redappletech.info/BeerGame/", image: "images/beer_game.png" },
            { name: "NeonBall", nameToShow: "Neon Ball", url: "https://game.redappletech.info/NeonBallConstruct/", image: "./images/neon_ball.png" },
            { name: "OttoToTheRescue", nameToShow: "Otto To The Rescue", url: "https://game.redappletech.info/OttoToTheRescueWeb/", image: "./images/otto_to_the_rescue.png" },
            { name: "CircleBall", nameToShow: "Circle Ball", url: "https://game.redappletech.info/CircleBall/", image: "images/circle_ball.png" },
            { name: "RunMerleRun", nameToShow: "Run Merle Run", url: "https://game.redappletech.info/RunMerleRun-Web/", image: "./images/run_merle_run.png" },
            { name: "NinjaJumpHero", nameToShow: "Ninja Jump Hero", url: "https://game.redappletech.info/NinjaJumpHero/", image: "images/ninja_jump_hero.png" },
            { name: "PenaltyKicks", nameToShow: "Penalty Blast", url: "https://game.redappletech.info/PenaltyKicks/", image: "images/penalty_kicks.png" },
            { name: "HitTheWicket", nameToShow: "Hit The Wicket", url: "https://game.redappletech.info/HitTheWicket//", image: "images/hit_the_wicket.png" },
            { name: "RedJumper", nameToShow: "Red Jumper", url: "https://game.redappletech.info/RedJumper/", image: "./images/red_jumper.png" },
            { name: "BreakOut", nameToShow: "BreakOut", url: "https://game.redappletech.info/BreakOut/", image: "./images/break_out.png" },
            { name: "RetroSpeed", nameToShow: "Retro Speed", url: "https://game.redappletech.info/RetroSpeed/", image: "./images/retro_speed.png" },
            { name: "CrazyGirl", nameToShow: "Crazy Girl", url: "https://game.redappletech.info/CrazyGirl/", image: "./images/crazy_girl.png" },
            { name: "SpinWheel", nameToShow: "Spin Wheel", url: "https://game.redappletech.info/SpinWheel/", image: "./images/wheel_spin.png" },
            { name: "SuperMonkey", nameToShow: "Super Monkey", url: "https://game.redappletech.info/SuperMonkey/?timer=180", image: "./images/super_monkey.png" },
            { name: "JetSkiRush", nameToShow: "Jet Ski Rush", url: "https://game.redappletech.info/JetSkiRush/", image: "images/jet_ski_rush.png" },
            { name: "ArithematicChallenge", nameToShow: "Arithematic Challenge", url: "https://game.redappletech.info/ArithematicChallenge/", image: "images/arithematic_challeneg.png" },
            { name: "TurkeyAdventure", nameToShow: "Turkey Adventure", url: "https://game.redappletech.info/TurkeyAdventure/", image: "images/turkey_adventure.png" },
            { name: "Bratib", nameToShow: "Bratib", url: "https://game.redappletech.info/Bratib/?lang=eng", image: "images/bratib.png" },
            { name: "PhotonHighway", nameToShow: "Photon Highway", url: "https://game.redappletech.info/PhotonHighway/", image: "images/photon_highway.png" },
            { name: "DeliveryIt", nameToShow: "Delivery It", url: "https://game.redappletech.info/DeliveryIt/", image: "images/delivery_it.png" },


            // { name: "DestroyBoxes", url: "https://game.redappletech.info/DestroyBoxes/", image: "images/destroy_box.png" },
            // { name: "GunShot", url: "https://game.redappletech.info/GunShot/", image: "./images/gun_shot.png" },
            // { name: "Match3", url: "https://game.redappletech.info/Match3/", image: "./images/match_3.png" },


            // { name: "CandyMinion", nameToShow: "Candy Minion", url: "http://68.183.90.9:3000/games/candy-minion/index.html", image: "./images/candy_minion.png" },
            // { name: "CannonBlaster", nameToShow: "Cannon Blaster", url: "http://68.183.90.9:3000/games/cannon-blaster-game/index.html", image: "./images/cannon_blaster.png" },
            // { name: "ChargeIt", nameToShow: "Charge It", url: "http://68.183.90.9:3000/games/charge-it/index.html", image: "./images/charge_it.png" },
            // { name: "ConnectMerge", nameToShow: "Connect Merge", url: "http://68.183.90.9:3000/games/connect-merge/index.html", image: "./images/connect_merge.png" },
            // { name: "CrazyJump", nameToShow: "Crazy Jump", url: "http://68.183.90.9:3000/games/crazy-jump/index.html", image: "./images/crazy_jump.png" },
            // { name: "CrossPath", nameToShow: "Cross Path", url: "http://68.183.90.9:3000/games/cross-path/index.html", image: "./images/cross_path.png" },
            // { name: "CubeJump", nameToShow: "Cube Jump", url: "http://68.183.90.9:3000/games/cube-jump/index.html", image: "./images/cube_jump.png" },
            // { name: "DesertRoad", nameToShow: "Desert Road", url: "http://68.183.90.9:3000/games/desert-road/index.html", image: "./images/desert_road.png" },
            // { name: "DottedFill", nameToShow: "Dotted Fill", url: "http://68.183.90.9:3000/games/dotted-fill/index.html", image: "./images/dotted_fill.png" },
            // { name: "DunkHoop", nameToShow: "Dunk Hoop", url: "http://68.183.90.9:3000/games/dunk-hoop/index.html", image: "./images/dunk_hoop.png" },
            // { name: "DunkShot", nameToShow: "Dunk Shot", url: "http://68.183.90.9:3000/games/dunk-shot/index.html", image: "./images/dunk_shot.png" },
            // { name: "Fill", nameToShow: "Fill", url: "http://68.183.90.9:3000/games/fill/index.html", image: "./images/fill.png" },
            // { name: "FilledGlass", nameToShow: "Filled Glass", url: "http://68.183.90.9:3000/games/filled-glass/index.html", image: "./images/filled_glass.png" },
            // { name: "GreedyRabbit", nameToShow: "Greedy Rabbit", url: "http://68.183.90.9:3000/games/greedy-rabbit/index.html", image: "./images/greedy_rabbit.png" },
            // { name: "SliceFruit", nameToShow: "Slice Fruit", url: "http://68.183.90.9:3000/games/fruit-slice/index.html", image: "./images/fruit_slice.png" },
            // { name: "FuritMaster", nameToShow: "Furit Master", url: "http://68.183.90.9:3000/games/furit-master/index.html", image: "./images/furit_master.png" },
            // { name: "GateRunner", nameToShow: "Gate Runner", url: "http://68.183.90.9:3000/games/gate-runner/index.html", image: "./images/gate_runner.png" },
            // { name: "KnifeNinja", nameToShow: "Knife Ninja", url: "http://68.183.90.9:3000/games/knife-Ninja/index.html", image: "./images/knife_ninja.png" },
            // { name: "HappyGlass", nameToShow: "Happy Glass", url: "http://68.183.90.9:3000/games/happy-glass/index.html", image: "./images/happy_glass.png" },
            // { name: "HousePainter", nameToShow: "House Painter", url: "http://68.183.90.9:3000/games/house-paint/index.html", image: "./images/house_paint.png" },
            // { name: "Igloria", nameToShow: "Igloria", url: "http://68.183.90.9:3000/games/igloria/index.html", image: "./images/igloria.png" },
            // { name: "JigsawDeluxe", nameToShow: "Jigsaw Deluxe", url: "http://159.89.174.49:4000/games/jigsaw-puzzle/", image: "./images/jigsaw_puzzle.png" },
            // { name: "MrGun", nameToShow: "Mr Gun", url: "http://68.183.90.9:3000/games/mr-gun/index.html", image: "./images/mr_gun.png" },
            // { name: "MergeFish", nameToShow: "Merge Fish", url: "http://68.183.90.9:3000/games/merge-fish/index.html", image: "./images/merge_fish.png" },
            // { name: "MergeCafe", nameToShow: "Merge Cafe", url: "http://68.183.90.9:3000/games/merge-cafe/index.html", image: "./images/merge_cafe.png" },
            // { name: "MasterSudoku", nameToShow: "Master Sudoku", url: "http://68.183.90.9:3000/games/master-sudoku/index.html", image: "./images/master_sudoku.png" },
            // { name: "Make5", nameToShow: "Make 5", url: "http://68.183.90.9:3000/games/make-5/index.html", image: "./images/make_5.png" },
            // { name: "Ludo", nameToShow: "Ludo", url: "http://68.183.90.9:3000/games/ludo/index.html", image: "./images/ludo.png" },
            // { name: "Make7", nameToShow: "Make 7", url: "http://68.183.90.9:3000/games/make-7/index.html", image: "./images/make_7.png" },
            // { name: "RollTheBall", nameToShow: "Roll The Ball", url: "http://68.183.90.9:3000/games/roll-the-ball/index.html", image: "./images/roll_the_ball.png" },
            // { name: "Nonstop4Letters", nameToShow: "Nonstop 4 Letters", url: "http://68.183.90.9:3000/games/nonstop-4-letter/index.html", image: "./images/nonstop_4_letter.png" },
            // { name: "NumberMaze", nameToShow: "Number Maze", url: "http://68.183.90.9:3000/games/number-maze/index.html", image: "./images/number_maze.png" },
            // { name: "PickMeUp", nameToShow: "Pick Me Up", url: "http://68.183.90.9:3000/games/pick-me-up/index.html", image: "./images/pick_me_up.png" },
            // { name: "PunchBox", nameToShow: "Punch Box", url: "http://68.183.90.9:3000/games/punch-box/index.html", image: "./images/punch_box.png" },
            // { name: "QuickMath", nameToShow: "Quick Math", url: "http://68.183.90.9:3000/games/quick-math/index.html", image: "./images/quick_math.png" },
            // { name: "QuizMaster", nameToShow: "Quiz Master", url: "http://68.183.90.9:3000/games/quiz-master/index.html", image: "./images/quiz_master.png" },
            // { name: "GalacticWar", nameToShow: "Galactic War", url: "http://159.89.174.49:4000/games/galaxy-war/", image: "./images/galaxy_war.png" },
            // { name: "Solitaire", nameToShow: "Solitaire", url: "http://68.183.90.9:3000/games/solitaire/index.html", image: "./images/solitaire.png" },
            // { name: "TileMasterMatch", nameToShow: "Tile Master Match", url: "http://68.183.90.9:3000/games/tile-master-match/index.html", image: "./images/tile_master_match.png" },
            // { name: "WordMaster", nameToShow: "Word Master", url: "http://68.183.90.9:3000/games/word-master/index.html", image: "./images/word_master.png" },
            // { name: "SolitaireNew", nameToShow: "Solitaire New", url: "http://68.183.90.9:3000/games/solitaire-new/index.html", image: "./images/solitaire_new.png" },
            // { name: "KingOfBird", nameToShow: "King Of Bird", url: "http://68.183.90.9:3000/games/kink-of-bird/index.html", image: "./images/kink_of_bird.png" },
            // { name: "ProfessorBubble", nameToShow: "Professor Bubble", url: "http://68.183.90.9:3000/games/bubble-shooter/index.html", image: "./images/bubble_shooter.png" },
            // { name: "BlueBird", nameToShow: "Blue Bird", url: "http://68.183.90.9:3000/games/blue-bird/index.html", image: "./images/blue_bird.png" },
            // { name: "FireNumber", nameToShow: "Fire Number", url: "http://68.183.90.9:3000/games/fire-number/index.html", image: "./images/fire_number.png" },
            // { name: "FrontLine", nameToShow: "Front Line", url: "http://68.183.90.9:3000/games/frontline/index.html", image: "./images/front_line.png" },
            // { name: "NeonBrick", nameToShow: "Neon Brick", url: "http://68.183.90.9:3000/games/neon-brick/index.html", image: "./images/neon_brick.png" },
            // { name: "NeonRun", nameToShow: "Neon Run", url: "http://68.183.90.9:3000/games/neon-run/index.html", image: "./images/neon_run.png" },
            // { name: "Snake", nameToShow: "Snake", url: "http://68.183.90.9:3000/games/snake/index.html", image: "./images/snake.png" },
            // { name: "SquareAdventure", nameToShow: "Square Adventure", url: "http://68.183.90.9:3000/games/square-adventure/index.html", image: "./images/square_adventure.png" },
            // { name: "Tetris", Tetris: "Make7", url: "http://68.183.90.9:3000/games/tetris/index.html", image: "./images/tetris.png" },
        ];
    };

};
//#endregion 
let constant = new Constant();
export { constant as Constant };